name: 'Version Validator'

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  validate-version:
    name: 'Validate package version'
    runs-on: ubuntu-latest
    steps:
      - name: 'Dump GitHub context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'Check whether the `version` in the `package.json` has been updated'
        env:
          NEW_COMMIT: ${{ github.event.after }}
          OLD_COMMIT: ${{ 'master' }}
          SCRIPT: ${{ '.github/workflows/scripts/validate-package-version-change.sh' }}
        run: bash $SCRIPT
