name: Site deployment

on:
  workflow_run:
    workflows: [Unit testing]
    types: [completed]
    branches: [main]
env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Build site
        run: cd site && yarn && yarn build
      - name: Deploy to S3 bucket
        run: aws s3 sync ./site s3://wordsgame-site --delete --exclude "./site/node_modules"
      # - name: invalidate Cloudfront configuration
      #   uses: chetan/invalidate-cloudfront-action@v2
      #   env:
      #     DISTRIBUTION: ${{ secrets.LEADGEN_PRODUCTION_DISTRIBUTION }}
      #     PATHS: "/"
      #     AWS_REGION: "us-east-1"
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
