name: Site deployment

on:
  workflow_run:
    workflows: [Unit testing]
    types: [completed]
    branches: [master]
env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Build site
        run: cd site && yarn && yarn build
      - name: Deploy to S3 bucket
        run: aws s3 sync ./site s3://wordsgame-site --delete --exclude "./site/node_modules/*"
